### ISSUE TITLE
Downloading a fresh copy of Match-One won't allow to generate with default settings

### ISSUE THREAD

**Issue by KumoKairo** [sschmid/Match-One#3]
It's settings are set to `Assembly-CSharp.csproj` by default, but the project is generated with the name of the folder which is `Match-One-master.csproj`
![image](https://user-images.githubusercontent.com/2943071/33210269-97e8921c-d12a-11e7-9409-f71423bcbfe3.png)
![image](https://user-images.githubusercontent.com/2943071/33210296-a7b5d1aa-d12a-11e7-828c-19b4722bb1d9.png)
Generating with the default properties shows an error of finding `Assembly-CSharp.csproj` and doesn't generate anything at all.

My guess is that it fails on a last step when everything is generated but it can't update the `csproj` file directly so it doesn't write anything on disk. I think this last step of updating the `.csproj` file shouldn't be so destructive. We can let everything generate and just leave our `.csproj` file alone, just warning the user that he's most likely have another project file name and it should be updated in the properties (we can even infer the name of the project based on different `.csproj` files in the root of the project.

Recap - downloading the package and trying to generate doesn't always work out of the box.

**Comment by sschmid** [comment]
Hi, for (to me) unknown reasons Unity doesn't generate a csproj file with a consistent name. For some, it's always Assembly-CSharp, for others it's ProjectName.csproj.

Solution and project files are not committed because Unity can regenerate them. If the name is different for you, you have to update the project path first or deactivate the CSProjPostProcessor.

See https://github.com/sschmid/Entitas-CSharp/issues/563

and 

https://github.com/sschmid/Entitas-CSharp/issues/572

As of Entitas 1.4.2, there's a ValidateProjectPathPreProcessor which will inform you about this issue when you generate and the project is missing or cannot be found
